version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ektaara
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ektaara
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      GOOGLE_APPLICATION_CREDENTIALS: /Users/ravi/Desktop/Ektaara/open-gem-gem/src/main/resources/poised-conduit-471220-b4-3db35b51d2f0.json (replaced with mounted value later for deployments)

volumes:
  pgdata:
